name: Tests

on:
  push:
    branches:
      - master
      - '*.x'
  pull_request:
  schedule:
    - cron: '*/30 * * * *'

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.3, 8.4]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo
          coverage: none

      - name: Install Composer dependencies
        run: |
          composer install --prefer-dist --no-interaction --no-progress
          rm -rf test && composer create-project doppar/doppar test

      - name: Copy environment file
        run: cp .env.example .env

      - name: Delete license file
        run: rm -f LICENSE.md

      - name: Generate app key
        run: php pool key:generate

      - name: Execute tests
        run: vendor/bin/phpunit